### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [rlister/slackbotsy#15]
I have inserted the Web API code using the 'Verification Token' as the API token

I have deployed to Heroku

I have setup Bot user

I have setup the Slash command /ping 

But when I try the /ping I get a **404 Client Error**

What am I doing wrong?

**Comment by rlister** [comment]
Hi @arnoldmarunda, have you tried this project: https://github.com/rlister/slackbotsy_example ?

It should be a complete working example that will get you started.

**Comment by arnoldtonderaimarunda** [comment]
thanks
